### ISSUE TITLE
Firebase API Key is exposed

### ISSUE THREAD

**Issue by sirhcm** [Coder-256/database-phoenix#1]
As the title says, your firebase API key is public, which could lead to your Firebase account being compromised. See [here](https://cloud.google.com/docs/authentication/api-keys#securing_an_api_key) for more information.

FYI, the outstanding file is [here](https://github.com/Coder-256/database-phoenix/blob/master/src/plugins/firebase.ts).

**Comment by jacob-greenfield** [comment]
I appreciate the concern, but I think the API key is supposed to be public. At first I was a bit skeptical but [look here](https://firebase.google.com/docs/web/setup#add_firebase_to_your_app). It seems to indicate that you should embed the API key in your public, browser JS code.

Now there is an alternative to embedding the API key in your code, which is [using implicit initialization](https://firebase.google.com/docs/web/setup#sdk_imports_and_implicit_initialization). I had looked into this at first, wondering if it would be more secure. However, I then realized: the `/__/firebase/init.js` URL of any Firebase Hosting project is automatically populated with code very similar to the file which you linked. (note that [`/__*` URLs are controlled by Firebase](https://firebase.google.com/docs/hosting/reserved-urls#top_of_page)). [Here is the automatic initialization file on this project's website](https://database-server-firebase.firebaseapp.com/__/firebase/init.js). That seems to be strong evidence to me that this particular API key can be made public. I chose to manually embed it in the project for easier local development rather than using implicit initialization which relies on cloud hosting. (but using implicit initialization is probably a better idea anyway for important apps, just in case you forget to update the API key!)

The link you sent appears to be about Google Cloud Platform API keys, which I believe are different from Firebase Web API keys. But I do absolutely appreciate the concern, thank you very much! (but in the future, an email would probably be a better option to give the dev a chance to fix the issue before they announce it). Let me know what you think.

**Comment by jacob-greenfield** [comment]
Also, just curious, what are you making?

**Comment by sirhcm** [comment]
Huh, that is odd that there isn't more information surrounding this. I think that based on what evidence you provided it is fair to say that the API key should be public. For now I just was planning to put the key in a .json file which would be part of the .gitignore, but I realize now that this still probably wont get around the fact visiting the website itself would likely reveal the API key (I haven't checked). [This](/christopherm99/cws-service) is the project that I am working on and which is in question (a community service website for Commonwealth).

**Comment by sirhcm** [comment]
Just checked, and it certainly is available on the deployed production website. There must be some other security measures.
